### ISSUE TITLE
Problems with tooltip colors in the cefou's dark theme

### ISSUE THREAD

**Issue by funlw65** [mse-org/mseuniverse#1]
The tooltip background is of a light color, making impossible to read the text. I tested this with a tooltip on a button from the toolbar of my application. And I have no idea how to change that at the application level, without tinkering with the cefou's theme...

I'm using MSEIDE 5.2 with freepascal 3.2.0

**Comment by fredvs** [comment]
Hello.

Thanks to report it, I will check cefou's code tonight.
Write you later.

Fre;D

**Comment by fredvs** [comment]
Re-hello.

Maybe there is a bug in cefou's theme, if you see something wrong, please do a pull-request.
I am not with my computer now, so I will check it tonight.

**Comment by fredvs** [comment]
Re-re hello.

Could you give a screenshot with the problem (I am not sure to understand what "tooltip" means).

**Comment by funlw65** [comment]
Ok, just a moment...

**Comment by funlw65** [comment]
Here is the screenshot
[image](https://drive.google.com/drive/folders/1S19QcRByMb9fNEcrJvWx0FUKPsvBYGIu?usp=sharing)

**Comment by funlw65** [comment]
See where the mouse pointer is? Under it, there is a light_yellow rectangle that should be of dark color, to let the text of the tooltip to be visible.

**Comment by fredvs** [comment]
Hum, it seems that is a bug in cefou's theme.

See here ideU with Carbon style:

![Capture d’écran_2021-02-02_16-47-28](https://user-images.githubusercontent.com/3421249/106625012-8e20e980-6576-11eb-8cce-203a14659a39.png)

I will check cefou's code tonight (I hope to find time).

**Comment by funlw65** [comment]
Thank you!

**Comment by fredvs** [comment]
Hello.

Hum...

I did try the cefou them with a simple app but get this error message:
![Capture d’écran_2021-02-02_20-06-41](https://user-images.githubusercontent.com/3421249/106649701-3e501b80-6592-11eb-9ad7-b52c7e27136a.png)

On the readme.txt there is:

> How to use :
> 1 - add ( dark.mfm , dark.pas , dark_mfm.pas , darkskin.pas ) to your project directory .
> 2 - add darkskin unit to you mainform uses clause .
> 
> have fun !

I did this but get error message.

I have to confess that I never used mse-themes, on my applications that have themes, I do it for all widgets, changing the color according the theme selected.

But maybe you can tell me how to install the cefou theme....

What appends if you dont add darkskin in uses section?

**Comment by fredvs** [comment]
What is your OS?

Here on Linux, I cannot make cefou theme work.

**Comment by funlw65** [comment]
Fred, I use it the same way as described by the author, I have all the files in the same folder with my app and only including darkskin as unit. Then my entire app has the dark theme. If I do not include it, then I have the default MSE theme... 

Try a new project from start. My operating system is based on Debian 10. Maybe to archive the theme I have and send it to you? I don't remember if I took it from here or the other places like gitlab or sourceforge...

**Comment by funlw65** [comment]
Here is my little [project](https://drive.google.com/file/d/1Ekx2RQpPSZzJExz26oENsOjUhBmuqF-d/view?usp=sharing)

**Comment by fredvs** [comment]
Hello.

Ha, your project works on Linux, great.
But yes, hint text color is white.

OK, I will try to find a solution.
Maybe...

If no I will manually change the color of your project to look like cefou theme.

**Comment by fredvs** [comment]
Hello.
I did not find a solution for the white text in hint of cefou theme.

Anyway, in attachment, your project using TFacecomp for every widget as template for face.

It is not exactly the cefou theme but not very far.
Of course you may custom it.
And tooltip has black text.

[mseguivpc.tar.gz](https://github.com/mse-org/mseuniverse/files/5914435/mseguivpc.tar.gz)

**Comment by funlw65** [comment]
Thank you Fred for your efforts, highly appreciated!

**Comment by funlw65** [comment]
Hi Fred,

Can you approve my topic on seide-msegui-talk forum (user funlw65)? Thank you!

**Comment by fredvs** [comment]
> Can you approve my topic on mseide-msegui-talk forum (user funlw65)? Thank you!

Hello.

Sorry but I dont understand.
What mseide-msegui-talk forum are you talking about?

There is the mailing list:
http://mseide-msegui-talk.13964.n8.nabble.com/

And the forum:
http://mse-org.111682.n8.nabble.com/

But I dont see user funlw65.

Or maybe I miss something.

Fre;D

**Comment by fredvs** [comment]
Ooops, indeed, I see funlw65

![Capture d’écran_2021-02-19_13-08-36](https://user-images.githubusercontent.com/3421249/108502984-f4ff0c00-72b3-11eb-9935-29211abbf6d3.png)

What is the problem, you should be able to post message.

It is possible that the first time it takes a few moment before to appear.

Fre;D

**Comment by funlw65** [comment]
It said I am not registered or that my topic needs to be approved... don't remember... it does not appear on my side :(

**Comment by funlw65** [comment]
I've sent a subscription request just now... Sorry, it was my fault.

**Comment by fredvs** [comment]
Hum, do you appear in "People"?
The thing with the mse mailing list is that we dont have control on it, Martin was the only one who had the passwords.

But there are still people that use it, so we keep it.

Please, could you give more info about the error message you get?

We did try to get the password and control of the mailing-list, I already sent message to lists.sourceforge.net to ask what to do, but no answer.

But yes, it is not cool to not have any control on it.

**Comment by fredvs** [comment]
> I've sent a subscription request just now... Sorry, it was my fault.

Ha ok, nice.

(But I maintain that we should have access to the mailing-list).

**Comment by funlw65** [comment]
Done, and reposted the topic which now is visible. Thank you!
